Repository microsoft/mssql-jdbc, pull requests merged in 2019-06, with the labels that each got.

#1016 Fix | Align DatabaseMetadata.getColumns with JDBC 4.3 Specifications
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java
  src/test/java/com/microsoft/sqlserver/jdbc/databasemetadata/DatabaseMetaDataTest.java
Labels: Can be Merged

#998 Feature | Introduce NTLM authentication mode
  azure-pipelines.yml
  build.gradle
  pom.xml
  src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java
  src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerDataSource.java
  src/main/java/com/microsoft/sqlserver/jdbc/KerbAuthentication.java
  src/main/java/com/microsoft/sqlserver/jdbc/NTLMAuthentication.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
  src/main/java/com/microsoft/sqlserver/jdbc/SSPIAuthentication.java
  src/main/java/mssql/security/provider/MD4.java
  src/test/java/com/microsoft/sqlserver/jdbc/NTLMConnectionTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java
  src/test/java/com/microsoft/sqlserver/jdbc/datatypes/TVPWithSqlVariantTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/fips/FipsTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/tvp/TVPTypesTest.java
  src/test/java/com/microsoft/sqlserver/testframework/AbstractSQLGenerator.java
  src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
  src/test/java/com/microsoft/sqlserver/testframework/Constants.java
  src/test/java/com/microsoft/sqlserver/testframework/DBTable.java
Labels: Awaiting Reviews, Public API

#1064 Fix | Misleading error message in CallableStatement
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java
  src/test/java/com/microsoft/sqlserver/jdbc/TestResource.java
  src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableMixedTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
Labels: Awaiting Reviews

#1044 Feature | Add new connection property 'useFmtOnly' to retrieve parameter metadata
  build.gradle
  pom.xml
  src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java
  src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerDataSource.java
  src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerPreparedStatement.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerFMTQuery.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerLexer.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParser.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
  src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/JDBCEncryptionDecryptionTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/ParserUtils.java
  src/test/java/com/microsoft/sqlserver/jdbc/TestUtils.java
  src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/fmtOnly/APITest.java
  src/test/java/com/microsoft/sqlserver/jdbc/fmtOnly/DeleteTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/fmtOnly/InsertTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/fmtOnly/LexerTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/fmtOnly/ParameterMetaDataTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/fmtOnly/SelectTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/fmtOnly/UpdateTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PQImpsTest.java
Labels: Awaiting Reviews, Public API

#1095 Update SQLServerConnection to store password hash for NTLM
  src/main/java/com/microsoft/sqlserver/jdbc/NTLMAuthentication.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
  src/test/java/com/microsoft/sqlserver/jdbc/NTLMConnectionTest.java
Labels: Awaiting Reviews

#1094 Changes after Fuzz Testing useFmtOnly
  src/main/java/com/microsoft/sqlserver/jdbc/ParameterUtils.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerFMTQuery.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParser.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
Labels: Awaiting Reviews
