Repository microsoft/mssql-jdbc, pull requests merged in 2022-03, with the labels that each got.

#1758 Added a check to prevent Implicit narrowing conversion in compound assignment
  src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
Labels: Awaiting Reviews

#1759 Add check for MSAL library when attempting ActiveDirectoryServicePrincipal authentication
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
Labels: PR Under Review

#1719 Added new connection string property prepareMethod to toggle use of sp_prepare
  src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java
  src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerDataSource.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
  src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/CallableStatementTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableStatementTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/BatchExecutionTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/unit/statement/PreparedStatementTest.java
  src/test/java/com/microsoft/sqlserver/testframework/AbstractTest.java
  src/test/java/com/microsoft/sqlserver/testframework/Constants.java
Labels: Public API

#1761 Fix test failure
  src/test/java/com/microsoft/sqlserver/jdbc/AlwaysEncrypted/CallableStatementTest.java
Labels: Under Review

#1763 Update version to 11.1.0
  README.md
  build.gradle
  mssql-jdbc_auth_LICENSE
  pom.xml
  src/main/java/com/microsoft/sqlserver/jdbc/SQLJdbcVersion.java
  src/samples/adaptive/pom.xml
  src/samples/alwaysencrypted/pom.xml
  src/samples/azureactivedirectoryauthentication/pom.xml
  src/samples/connections/pom.xml
  src/samples/constrained/pom.xml
  src/samples/dataclassification/pom.xml
  src/samples/datatypes/pom.xml
  src/samples/resultsets/pom.xml
  src/samples/sparse/pom.xml
Labels: Under Review

#1766 Add Configurable IPv6 Support
  src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java
  src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerConnection.java
  src/main/java/com/microsoft/sqlserver/jdbc/ISQLServerDataSource.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionPoolProxy.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java
  src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java
  src/test/java/com/microsoft/sqlserver/jdbc/SQLServerConnectionTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/connection/ConnectionTest.java
  src/test/java/com/microsoft/sqlserver/jdbc/connection/RequestBoundaryMethodsTest.java
Labels: Work in Progress, Public API
